# Generated by Django 5.2.8 on 2025-11-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RechercheUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_recherche', models.TextField(verbose_name='Question de recherche')),
                ('email_utilisateur', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
            ],
            options={
                'verbose_name': 'Recherche utilisateur',
                'verbose_name_plural': 'Recherches utilisateurs',
                'ordering': ['-date_creation'],
            },
        ),
    ]
