# Generated by Django 5.2.8 on 2025-11-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechercheutilisateur',
            name='resultats_recherche',
            field=models.JSONField(blank=True, null=True, verbose_name='Résultats de recherche'),
        ),
        migrations.AddField(
            model_name='rechercheutilisateur',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20),
        ),
    ]
