# Generated by Django 5.2.8 on 2025-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_rechercheutilisateur_resultats_recherche_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurAnonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('date_premiere_recherche', models.DateTimeField(auto_now_add=True)),
                ('nombre_recherches', models.IntegerField(default=0)),
                ('derniere_recherche', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utilisateur anonyme',
                'verbose_name_plural': 'Utilisateurs anonymes',
            },
        ),
    ]
