# Generated by Django 5.2.8 on 2025-11-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_utilisateuranonyme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UtilisateurAnonyme',
        ),
    ]
