# Generated by Django 5.2.8 on 2025-11-15 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_delete_utilisateuranonyme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Le commentaire doit contenir au moins 10 caractères')], verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CompteurVisiteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visites', models.PositiveIntegerField(default=0, verbose_name='Nombre de visites')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Compteur de visiteurs',
                'verbose_name_plural': 'Compteurs de visiteurs',
            },
        ),
    ]
