# Generated by Django 5.2.8 on 2025-11-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_commentaire_compteurvisiteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='approuve',
            field=models.BooleanField(default=True, verbose_name='Approuvé'),
        ),
    ]
