# Generated by Django 5.2.8 on 2025-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_commentaire_approuve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='nom',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='approuve',
            field=models.BooleanField(default=True, null=True, verbose_name='Approuvé'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='compteurvisiteurs',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='compteurvisiteurs',
            name='nombre_visites',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Nombre de visites'),
        ),
        migrations.AlterField(
            model_name='rechercheutilisateur',
            name='email_utilisateur',
            field=models.EmailField(max_length=254, null=True, verbose_name='Adresse Email'),
        ),
        migrations.AlterField(
            model_name='rechercheutilisateur',
            name='question_recherche',
            field=models.TextField(null=True, verbose_name='Question de recherche'),
        ),
    ]
